feat: add register endpoint
WiT-Mentor-2024/airbnb-like-app pull request #3
Opened 2024-10-17 15:04 UTC by taorminak

### **Changes Made:**

- Added a new endpoint: POST /register

Request Body:

username: string (required)
email: string (required, must be a valid email format)
password: string (required, minimum 8 characters)
first_name: string (optional)
last_name: string (optional)
address: string (optional)
phone_number: string (optional)

**Response:**

- On success, returns the newly created user object with a 200 status code.
- If the email is already registered, returns a 400 status code with an appropriate error message.

**Validation:**

- The request body is validated using Pydantic schemas to ensure that all required fields are present and correctly formatted.
- Passwords are hashed before being stored in the database for security.

2024-10-18 13:16 UTC, alinashabalina requested changes

2024-10-18 13:16 UTC, alinashabalina commented on main.py
> +    if db.query(User).filter(User.email == user.email).first():
Есть ощущение, что это полезная проверка, которая будет переиспользована большое количество раз, поэтому имеет смысл вынести из метода повыше, а тут переиспользовать

2024-10-18 13:16 UTC, alinashabalina commented on database.py
я бы в 35 строчке при Exception не печатала бы, лучше возвращать тогда уже с аргументами e

2024-10-18 13:16 UTC, alinashabalina commented on main.py
> +        raise HTTPException(status_code=400, detail="Email already registered")
кстати про всякие detail: я бы вынесла всю статичную инфу в файлик отдельный и оттуда импортировала, чтобы менять тексты ошибок в одном месте, а не по всему проекту потом.

но это не критично

2024-10-18 13:16 UTC, alinashabalina commented on main.py
> +    new_user = User(
возможно стоило бы ещё в User модельке сделать методы класса, которые бы все операции с челиком выполняли бы вне main.py

2024-10-21 15:18 UTC, taorminak commented on main.py
> +    if db.query(User).filter(User.email == user.email).first():
вынесла в отдельную функцию

2024-10-21 15:18 UTC, taorminak commented on database.py
вернула с аргументами

2024-10-21 15:18 UTC, taorminak commented on main.py
> +        raise HTTPException(status_code=400, detail="Email already registered")
вынесла в отдельный файлик

2024-10-21 15:18 UTC, taorminak commented on main.py
> +    new_user = User(
вынесла в функции класса

2024-10-21 15:19 UTC, taorminak commented
Внесены правки во втором коммите

2024-10-21 19:47 UTC, alinashabalina approved these changes

2024-10-21 19:47 UTC, alinashabalina commented on main.py
> +def is_email_registered(db, email: str) -> bool:
он же теперь в модельке есть, можно в следующей итерации убрать отсюда, раз ты его из него вызываешь

2024-10-21 20:14 UTC, merged